"""empty message

Revision ID: 010665c72002
Revises: 19846e4bc741
Create Date: 2019-03-30 10:29:58.350096

"""

# revision identifiers, used by Alembic.
revision = '010665c72002'
down_revision = '19846e4bc741'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('updates', sa.ARRAY(postgresql.JSON(astext_type=sa.Text())), nullable=True),
    sa.Column('projectId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['projects.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('updates')
    # ### end Alembic commands ###
