"""empty message

Revision ID: 19846e4bc741
Revises: None
Create Date: 2019-03-05 22:08:41.708576

"""

# revision identifiers, used by Alembic.
revision = '19846e4bc741'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revenues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rentalIncome', sa.Integer(), nullable=True),
    sa.Column('vacancyRate', sa.Float(), nullable=True),
    sa.Column('annualOpEx', sa.Integer(), nullable=True),
    sa.Column('analysisDuraion', sa.Integer(), nullable=True),
    sa.Column('growthRate', sa.Float(), nullable=True),
    sa.Column('projectId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['projects.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revenues')
    # ### end Alembic commands ###
